### ISSUE TITLE
KeyBitmap FromBGR24Array 

### ISSUE THREAD

**Issue by tgd-git** [OpenMacroBoard/OpenMacroBoard.SDK#19]
I am tinkering with setting GPU rendered graphics on a key. The GPU textures are always float4 (always with alpha channel, regardless of the fact if it is used or not). Now when reading these textures back from GPU to byte arrays it is at minimal cost (just a copy of the vram) but i am stuck with 4 channels. now stripping the 4th channel from that array requires a costly loop over the whole array. i would like to avoid that step.
I wish there would be at least BGRA32 or a more common RGBA32 option beside the BGR24 format. I understand that there is no point to care about the alpha channel on a key and omitting alpha reduces the amount of data to be sent. I wonder if one could still provide 4 channel images and the lib could just skip the 4th channel when sending the data to the device? sorry if i get anything wrong about how that works, i just wonder if the lib could be more convenient in case the source data is not BGR24.

**Comment by wischi-chr** [comment]
Hi @tgd-git 

I certainly can provide a way to construct a `KeyBitmap` from a four channel BGRA32 or RGBA32 but the performance gain would probably be negligible. Many macro boards expect the keys to be in a particular format und for some of them (Stream Deck MK2, Stream Deck XL, etc.) the keys even are JPEG encoded so before sending the keys over USB the library (StreamDeckSharp) even has to JPEG-encode the image which is far more costly than copying a buffer.

There are some performance optimizations already implemented, especially if the constructed KeyBitmap is reused the encoding (for example to jpeg) only happens once. But for stuff like videos (you can check out [the video example](https://github.com/OpenMacroBoard/OpenMacroBoard.ExampleCollection/tree/master/src/OpenMacroBoard.Examples.VideoPlayer)) the images have to be encoded to jpg for each frame and even that part of the code is faster than the max. frame-rate for most such macro devices.

So if I's implement that I'd probably just end up copying the buffer internally anyways because it's probably not worth the effort to rewrite everything internally to be a hand full of nanoseconds faster just to end up JPEG encoding the image later.

**Comment by tgd-git** [comment]
Thank you for the explanation, i see i was bit off in my thinking how the data is handled :) I am very surprised about the JPEG encoding. I see your point that this is the most costly part. You might still want to add a method for 4 channel input just for user convenience in some cases. 
Me personally took this little issue as an opportunity to learn a bit about compute shaders. Just want to try construct the right format on the gpu already before reading back and providing to the lib. Still on it though:) Thanks again for clarifying and the work on this nice lib anyway. Cheers

**Comment by wischi-chr** [comment]
In the new version (5.0.0 via nuget) there are two new methods `FromBgra32Array` and `FromRgba32Array` to create `KeyBitmaps`.

Details see source: https://github.com/OpenMacroBoard/OpenMacroBoard.SDK/blob/master/src/OpenMacroBoard.SDK/KeyBitmapBasicFactoryExtensions.cs

**Comment by tgd-git** [comment]
works like a charm, thanks for the update! feels much cleaner now.

![image](https://github.com/OpenMacroBoard/OpenMacroBoard.SDK/assets/2562637/e2114a24-c653-4903-9dca-138402c1fe01)

**Comment by wischi-chr** [comment]
👌
What's that node/graph editor you've screenshotted there? Is that something you have developed or some kind of tool? Looks nice.

**Comment by tgd-git** [comment]
thats the editor view for a visual programming language called vvvv, made in berlin. https://visualprogramming.net/
using it a lot. it is based on .net so it can use .net libraries and nugets too. its fun:)
